spring:
  data:
    mongodb:
      username: pamela
      password: pamela123
      host: localhost
      port: 27017
      database: chatbot
      authentication-database: admin
server:
  port: 8089
